name: CI

on: push

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        working-directory: emulator
        with:
          command: build
          args: --verbose --all-features
      - uses: actions-rs/cargo@v2
        working-directory: emulator
        with:
          command: test
          args: --verbose --all-features
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        working-directory: emulator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
