name: CI

on: push

jobs:
  cargo:
    runs-on: ubuntu-latest
    env:
      working-directory: ./emulator
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
